spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:8090"
      client:
        registration:
          frontend-app:
            provider: spring
            client-id: gateway-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8090/authorized"
            scope:
              - openid
              - profile
              - read
              - write
            client-name: gateway-app
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:8090"